// <auto-generated />
using System;
using Amora.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amora.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AmoraDbContext))]
    [Migration("20260525102248_RemovePetMood")]
    partial class RemovePetMood
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amora.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmoraGems")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("BannedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PreferNotToSay");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Interests")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastCoPresenceCoinDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastPetCoinRewardDate")
                        .HasColumnType("date");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PetCoins")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string[]>("Photos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("RequiresPasswordUpdate")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AmoraGems = 0,
                            AvatarUrl = "alice.png",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Amora Alice",
                            Gender = "PreferNotToSay",
                            IsBanned = false,
                            IsProfileComplete = false,
                            PetCoins = 0,
                            Photos = new string[0],
                            RequiresPasswordUpdate = false,
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AmoraGems = 0,
                            AvatarUrl = "bob.png",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Amora Bob",
                            Gender = "PreferNotToSay",
                            IsBanned = false,
                            IsProfileComplete = false,
                            PetCoins = 0,
                            Photos = new string[0],
                            RequiresPasswordUpdate = false,
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AmoraGems = 0,
                            AvatarUrl = "carol.png",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Amora Carol",
                            Gender = "PreferNotToSay",
                            IsBanned = false,
                            IsProfileComplete = false,
                            PetCoins = 0,
                            Photos = new string[0],
                            RequiresPasswordUpdate = false,
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AmoraGems = 0,
                            AvatarUrl = "admin.png",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Amora Admin",
                            Email = "admin@amora.app",
                            Gender = "PreferNotToSay",
                            IsBanned = false,
                            IsProfileComplete = false,
                            PetCoins = 0,
                            Photos = new string[0],
                            RequiresPasswordUpdate = false,
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Amora.Domain.Entities.ChatReadState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId", "MatchId")
                        .IsUnique();

                    b.ToTable("ChatReadStates", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.IapPurchaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GemsGranted")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Platform", "TransactionId")
                        .IsUnique();

                    b.ToTable("IapPurchaseRecords", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.IapWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<string>("RawPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "EventId")
                        .IsUnique();

                    b.ToTable("IapWebhookEvents", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.MatchConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("UserAId", "Status");

                    b.HasIndex("UserBId", "Status");

                    b.ToTable("MatchConnections", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.MatchDailyMediaUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImagesSent")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "UserId", "UsageDate")
                        .IsUnique();

                    b.ToTable("MatchDailyMediaUsages", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveBuffsJson")
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveHighHpDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("HpGainWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HpGainedIn24h")
                        .HasColumnType("integer");

                    b.Property<int>("HpSnapshotCount")
                        .HasColumnType("integer");

                    b.Property<double>("HpSnapshotSum")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastHpSnapshotDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPartnerMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OnlineBonusGrantedToday")
                        .HasColumnType("boolean");

                    b.Property<long>("Rp")
                        .HasColumnType("bigint");

                    b.Property<int>("RpFromTextToday")
                        .HasColumnType("integer");

                    b.Property<int>("RpFromVoiceToday")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RpStatsDate")
                        .HasColumnType("date");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("IsFrozen", "LastInteractionAt");

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.PetStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetId", "CreatedAt");

                    b.ToTable("PetStateHistories", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.PetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmoraGemsDelta")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("PetCoinsDelta")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PetTransactions", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.PetVibeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CleanAudioUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("DurationSec")
                        .HasColumnType("double precision");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsMonotone")
                        .HasColumnType("boolean");

                    b.Property<double>("Pitch")
                        .HasColumnType("double precision");

                    b.Property<double>("PitchVariance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("PetVibeData", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.ShopItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PriceAmoraGems")
                        .HasColumnType("integer");

                    b.Property<int>("PricePetCoins")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ShopItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000001-0001-4001-8001-000000000001"),
                            Code = "energy_cookie",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bánh Quy Năng Lượng",
                            EffectJson = "{\"hp\":30}",
                            IsActive = true,
                            ItemType = "Consumable",
                            Name = "Bánh Quy Năng Lượng",
                            PriceAmoraGems = 0,
                            PricePetCoins = 50,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f1000001-0001-4001-8001-000000000002"),
                            Code = "gentle_bath",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sữa Tắm Dịu Nhẹ",
                            EffectJson = "{\"hp\":20}",
                            IsActive = true,
                            ItemType = "Consumable",
                            Name = "Sữa Tắm Dịu Nhẹ",
                            PriceAmoraGems = 5,
                            PricePetCoins = 80,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f1000001-0001-4001-8001-000000000003"),
                            Code = "growth_potion",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Lọ Thuốc Tăng Trưởng",
                            EffectJson = "{\"buff\":\"DoubleVoiceRp\",\"hours\":6}",
                            IsActive = true,
                            ItemType = "Buff",
                            Name = "Lọ Thuốc Tăng Trưởng",
                            PriceAmoraGems = 10,
                            PricePetCoins = 120,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f1000001-0001-4001-8001-000000000004"),
                            Code = "resonance_candy",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kẹo Cộng Hưởng",
                            EffectJson = "{\"rp\":10}",
                            IsActive = true,
                            ItemType = "Consumable",
                            Name = "Kẹo Cộng Hưởng",
                            PriceAmoraGems = 0,
                            PricePetCoins = 40,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f1000001-0001-4001-8001-000000000005"),
                            Code = "revival_flask",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bình Hồi Sinh",
                            EffectJson = "{\"hp\":50}",
                            IsActive = true,
                            ItemType = "Revival",
                            Name = "Bình Hồi Sinh",
                            PriceAmoraGems = 20,
                            PricePetCoins = 200,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f1000001-0001-4001-8001-000000000006"),
                            Code = "fire_fox_skin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Da Cáo Lửa",
                            EffectJson = "{}",
                            IsActive = true,
                            ItemType = "Cosmetic",
                            Name = "Da Cáo Lửa",
                            PriceAmoraGems = 15,
                            PricePetCoins = 150,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f1000001-0001-4001-8001-000000000007"),
                            Code = "memory_collar",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Vòng Cổ Kỷ Niệm",
                            EffectJson = "{}",
                            IsActive = true,
                            ItemType = "Cosmetic",
                            Name = "Vòng Cổ Kỷ Niệm",
                            PriceAmoraGems = 30,
                            PricePetCoins = 300,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Amora.Domain.Entities.UserBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockerId");

                    b.HasIndex("BlockerId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("UserBlocks", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.UserInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId", "ShopItemId")
                        .IsUnique();

                    b.ToTable("UserInventories", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.UserReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId", "TargetUserId")
                        .IsUnique();

                    b.ToTable("UserReports", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.VoiceComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("CommenterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "CommenterId")
                        .IsUnique();

                    b.HasIndex("PostId", "Status");

                    b.ToTable("VoiceComments", (string)null);
                });

            modelBuilder.Entity("Amora.Domain.Entities.VoicePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PosterId", "Status");

                    b.ToTable("VoicePosts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AudioUrl = "https://amora-s3.bucket.com/voices/post_1.m4a",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MatchCount = 0,
                            PosterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Open"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AudioUrl = "https://amora-s3.bucket.com/voices/post_2.m4a",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MatchCount = 1,
                            PosterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Open"
                        });
                });

            modelBuilder.Entity("Amora.Domain.Entities.ChatReadState", b =>
                {
                    b.HasOne("Amora.Domain.Entities.MatchConnection", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amora.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amora.Domain.Entities.IapPurchaseRecord", b =>
                {
                    b.HasOne("Amora.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amora.Domain.Entities.Pet", b =>
                {
                    b.HasOne("Amora.Domain.Entities.MatchConnection", "Match")
                        .WithOne()
                        .HasForeignKey("Amora.Domain.Entities.Pet", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Amora.Domain.Entities.PetStateHistory", b =>
                {
                    b.HasOne("Amora.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Amora.Domain.Entities.PetTransaction", b =>
                {
                    b.HasOne("Amora.Domain.Entities.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Amora.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amora.Domain.Entities.PetVibeData", b =>
                {
                    b.HasOne("Amora.Domain.Entities.VoicePost", "Post")
                        .WithOne("PetVibeData")
                        .HasForeignKey("Amora.Domain.Entities.PetVibeData", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Amora.Domain.Entities.UserInventory", b =>
                {
                    b.HasOne("Amora.Domain.Entities.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amora.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amora.Domain.Entities.VoiceComment", b =>
                {
                    b.HasOne("Amora.Domain.Entities.VoicePost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Amora.Domain.Entities.VoicePost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PetVibeData");
                });
#pragma warning restore 612, 618
        }
    }
}
