name: ci

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Amora.BE.sln

      - name: Build
        run: dotnet build Amora.BE.sln -c Release --no-restore

      - name: Test
        run: echo "Skipping tests for now" # dotnet test tests/Amora.Application.Tests/Amora.Application.Tests.csproj -c Release --no-build
