name: Deploy to Google Cloud

on:
  push:
    branches:
      - main # Khi có code mới đẩy lên nhánh main sẽ tự động chạy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Di chuyển vào thư mục code
          cd ~/AMORA.BE
          
          # Kéo code mới nhất từ nhánh main (Xóa đè các file bị sửa trên server nếu có)
          git fetch origin main
          git reset --hard origin/main
          git clean -fd
          git pull origin main
          
          # Dọn dẹp các container bị treo (để tránh lỗi Conflict)
          docker-compose down
          docker rm -f amora-api || true
          
          # Build lại và chạy các thay đổi mới
          docker-compose up -d --build
